export const featuredPlotProperties = [
  {
    id: 'plot-ptn-600',
    title: 'Green Enclave Plot 600',
    category: 'buy',
    property_type: 'plot',
    city: 'Patna',
    location: 'Danapur, Patna',
    area: 600,
    price: 2850000,
    description: 'Corner 600 sqft freehold plot inside a gated lane near Danapur station. Best suited for a compact duplex home with immediate road access and water line connectivity.',
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80'],
    status: 'approved',
    amenities: ['Road-facing', 'Drainage', 'Street lights'],
    projectStatus: 'Ready to register',
    configurations: 'Residential Plot'
  },
  {
    id: 'plot-del-1200',
    title: 'North Vista Plot 1200',
    category: 'buy',
    property_type: 'plot',
    city: 'Delhi',
    location: 'Najafgarh, Delhi',
    area: 1200,
    price: 9600000,
    description: 'Rectangular 1200 sqft plot with 30-ft approach road in a fast-growing residential pocket of Najafgarh. Ideal for builder floor development with strong rental demand nearby.',
    images: ['https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80'],
    status: 'approved',
    amenities: ['30-ft road', 'Metro connectivity zone', 'Electricity available'],
    projectStatus: 'Ready to build',
    configurations: 'Residential Plot'
  },
  {
    id: 'plot-lko-900',
    title: 'Riverfront Plot 900',
    category: 'buy',
    property_type: 'plot',
    city: 'Lucknow',
    location: 'Gomti Nagar Extension, Lucknow',
    area: 900,
    price: 5200000,
    description: 'Premium 900 sqft east-facing plot in Gomti Nagar Extension with clean title and nearby township amenities. Excellent fit for first-home construction in a planned sector.',
    images: ['https://images.unsplash.com/photo-1566904889185-74b0d7ff9635?auto=format&fit=crop&w=1200&q=80'],
    status: 'approved',
    amenities: ['East-facing', 'Park nearby', 'Wide internal road'],
    projectStatus: 'Resale ready',
    configurations: 'Residential Plot'
  },
  {
    id: 'plot-jpr-1500',
    title: 'Pink City Plot 1500',
    category: 'buy',
    property_type: 'plot',
    city: 'Jaipur',
    location: 'Jagatpura, Jaipur',
    area: 1500,
    price: 7400000,
    description: 'Large 1500 sqft plot in Jagatpura with smooth connectivity to airport road and educational hubs. Perfect for premium villa construction with excellent future appreciation.',
    images: ['https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80'],
    status: 'approved',
    amenities: ['Corner option', 'Sewer line', 'School proximity'],
    projectStatus: 'Under resale',
    configurations: 'Residential Plot'
  },
  {
    id: 'plot-ind-800',
    title: 'Metro Edge Plot 800',
    category: 'buy',
    property_type: 'plot',
    city: 'Indore',
    location: 'Super Corridor, Indore',
    area: 800,
    price: 3600000,
    description: 'Smart-sized 800 sqft plot close to Super Corridor IT belt. Suitable for compact modern housing and ideal for buyers looking for low-entry investment in Indore.',
    images: ['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80'],
    status: 'approved',
    amenities: ['IT corridor access', 'Public transport', 'Boundary markers'],
    projectStatus: 'Ready for possession',
    configurations: 'Residential Plot'
  },
  {
    id: 'plot-hyd-2000',
    title: 'Tech Valley Plot 2000',
    category: 'buy',
    property_type: 'plot',
    city: 'Hyderabad',
    location: 'Shamshabad, Hyderabad',
    area: 2000,
    price: 12400000,
    description: 'Spacious 2000 sqft gated community plot near airport growth corridor. Good option for luxury villa development with strong end-user demand and commercial spillover.',
    images: ['https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=1200&q=80'],
    status: 'approved',
    amenities: ['Gated layout', 'Clubhouse access', 'Blacktop roads'],
    projectStatus: 'Investor resale',
    configurations: 'Residential Plot'
  },
  {
    id: 'plot-pun-1100',
    title: 'Canal View Plot 1100',
    category: 'buy',
    property_type: 'plot',
    city: 'Pune',
    location: 'Wagholi, Pune',
    area: 1100,
    price: 6800000,
    description: 'North-facing 1100 sqft plot in Wagholi with quick access to Kharadi business district. Suitable for self-use plus long-term capital growth in a high-demand suburb.',
    images: ['https://images.unsplash.com/photo-1472220625704-91e1462799b2?auto=format&fit=crop&w=1200&q=80'],
    status: 'approved',
    amenities: ['North-facing', 'Water connection', 'Market nearby'],
    projectStatus: 'Ready to transfer',
    configurations: 'Residential Plot'
  },
  {
    id: 'plot-ahm-1400',
    title: 'Sabarmati Plot 1400',
    category: 'buy',
    property_type: 'plot',
    city: 'Ahmedabad',
    location: 'South Bopal, Ahmedabad',
    area: 1400,
    price: 7900000,
    description: 'Freehold 1400 sqft plot in South Bopal with broad internal roads and active neighborhood development. Great for multi-level independent house construction.',
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80'],
    status: 'approved',
    amenities: ['Freehold', 'Paved roads', 'Hospital proximity'],
    projectStatus: 'Ready to build',
    configurations: 'Residential Plot'
  }
];

export default featuredPlotProperties;
